# Generated by Django 3.2.20 on 2023-08-07 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Security',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issuer', models.CharField(max_length=200)),
                ('isin', models.CharField(max_length=12)),
                ('cusip', models.CharField(max_length=9)),
                ('bond_type', models.CharField(max_length=20)),
                ('ticker_symbol', models.CharField(max_length=3)),
                ('coupon_rate', models.DecimalField(decimal_places=2, max_digits=3)),
                ('maturity_date', models.DateTimeField()),
                ('face_value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('current_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('yield_to_maturity', models.DecimalField(decimal_places=2, max_digits=3)),
                ('rating', models.CharField(choices=[('AAA', 'AAA'), ('AA', 'AA'), ('A', 'A'), ('BBB', 'BBB'), ('BB', 'BB'), ('B', 'B'), ('CCC', 'CCC'), ('CC', 'CC'), ('C', 'C'), ('D', 'D')], max_length=3)),
                ('status', models.CharField(choices=[('Completed', 'Completed'), ('Released', 'Released'), ('Canceled', 'Canceled'), ('Project_Abandoned', 'Project_Abandoned'), ('Defaulted', 'efaulted'), ('Waiting_for_District_Clearance', 'Waiting_for_District_Clearance'), ('Category_X_(TBD)', 'Category_X_(TBD),'), ('Active', 'Active'), ('B-Permit_in_Deficit', 'B-Permit_in_Deficit'), ('Bond_Replaced', 'Bond_Replaced')], max_length=100)),
            ],
        ),
    ]
