# Generated by Django 3.2.2 on 2023-08-09 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
