# Generated by Django 3.2.2 on 2023-08-09 02:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_report_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='Watchlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.trade')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.dbuser')),
            ],
            options={
                'unique_together': {('user', 'trade')},
            },
        ),
    ]
